
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.2
      with:
        key: MIIJKQIBAAKCAgEAvChO/k926HCog4hXYqQQGb25S75KqaJI/z1B//5UxvwU5mdDnRZ5/pJjYTAcL1tgZzlwWwSjOsKbLZTVjM+oWXxEopwRszh8A2g2ENLU6O6OcSaNR7OW7zWDD8QobIAW3ZWFAwuWagxpAAHV5VYEqDoEaZHXnmTMMzTWTMWwfCN2Xa5O59txy1gxsS9fs/F2EYrahX/xYt2TPymZ2aBz2o3UFiTx668Oqwq7EQv4bH+1a49YDEZK7xs265XYsswXCU6PWBCWc+0n5QaZlgUHqfmnUBSW+0p9on25Xx8C1Gh2oJj1btOX/C1Z/gbTjC4qdz8q4rKgbaLEpxFmATRQ6oH9Au0zr00kkckjemOVANAj5ZvuzQhECL83Thb6kvLRqdvXzUwzZqQhJ/HLjrvEzFLlR5Lpit5juM8PuEx7c5YROvZzWtNUl61bKlWqGj5MCHpvTeAC5rq1UgZPJbBZbSIbnydrDQ6c7m9cDR7Js7cIrnAci2TbcwhJxKBlM6XsQF+x2RoMTXK2rtLfo+nSqPG001vDsiN3/eBmD0EeqhFd7ny/YtQnvsQeD3jpa0jZbXBVACOqorjUq6sRYgAmJRnrAqpfXS246AlyNIgrslkkB31DtQmZ2MgzPSL40JxPZzIqs+cGeykWHdcJMlseH9PMb3zoHJNGscbBZmuQz6MCAwEAAQKCAgAyqivzIJSlLEjD+j+FiSXouISfl6LlIJTFXcpa0zIizpgWHnI/Z2D8IpDuB5VfTxybTwUpDQui8+nzESObogLz7ZlRq/K8LpZ+GF6OkybPfgUPBNGAICShTuh2o1w7MxZ1HiDN3B3pemP/o37kHRBt+AleH+5OcVfm5fBahdTq6GWj/h6zIgz3M01WJ6p+eqNPP/NthTELbRyMIniR+DmZ/RzBxbr6uo2Zku8iPPXsyUqhptyPmZHt5ocYUqYiJwCA+g1xKi5JEu/uJKPQmJQiud3Km3C4Q6umyHHU4jXR2jsvLWDRMdq4BcI4u7/U/E1lBLZYir7WJsELN40e/+ZVeMpOG6SWH516vXoU5r3UvIbwTrr1j5yPNz9+1J5ywSgGtN+kNgTuip22EZWhCzNr2S4hNpAIcIjtWqdmVLrq9XaDHeRkDdbNOTiCD+9z5o76D5l4cam/Wx9nSpeTnmXFY75KdDuL1J15nMwcvapA2ARGEkc87TJ7qBfeZiBRbBLzwpY17tBZTPQM9ehc949gRww3cICOAJzPx9DXY5qmFtY3U5wBM5mbYzEKVt2X+YiWSNIaxMZiIrC9wFdF97eDAc4h5aj42N1PEgjy4vavGgl4n5zjdApDoLIyrYQI+LvutNE/WG7SGyVl3ZqL17Of84iO4Bw+8S2IAGr/e5ZhUQKCAQEA5ozNygI+8t1JaKh/f1sfWy8HmAAPA99ZPgbdFsTwmiglDoSKG1aNHApOjLRBpRtdkg6IqHhar6QX6Kke9NBVKp7sOOHqgS6+aDILPjxV5dZLa63q14mSXGG2c17UYcmZ89U4JvPa8UlpNBagFDd7Ucs7482TZB/G9lHECoaaGLXQTvw0RjzHDguS3CIxoZjRBl3eVdFg1U+khZNJ39mdEonNg2fy949uVtJYZTXU1LD5gXl8OuArgDsAU7ox5Fc1f0OGqiyyawOP6UuMhx9CQDs9esFAn6ZH+jH8fQ4Qdn8BcpOliXJnoSdqHlJBdQgRz3iU0UyL+HjiSbSMrrkaOwKCAQEA0O2EntpQn6BVlCB7TrlJRra8xVFXFW/btZsuQPaj/cfiIA1PUsq1TOXv569Sh/AjPLKPcJUIxi3HlLtGYG1H/Y0i98a1TAcx8wrBOgUTC1gQM6cdU47UB4lR8B4Gc94QDtf1uc2rW/2m4haA4A1U1tclEv+zezjLcJpas4LHYxvVuHN8VrrLEErQndaS6KpNRcC7pzt3t3btHG94NlgD9xeVKSpWnHpjEixBwzRo3y4vhyhoJS4dFv1wqQrDFz8MQBKBNjGdfUMxHK8BinKqbs9ORCyPPOIXAcRzECdhru7Tfs3CMgbf5u35/fa0wBYWu69fAWJVydA3TJy+fE3huQKCAQEAitNIa5a0nvt+46VquJ5/ICIOmYmXgQZxr3bklHxcQQdhYP+QRev1JmhSakl0qd3zlypnQcLPIKpXt0J3IIV+cx6lMY9f7Q/fmdBgksY0FyTV324nVkhBuJ0iBxCYJJYHvRqsKFB4iwhgb/wbwnCyMkuFsaOtWAIGhXYw7QGmMrDwUU9ujsi0OBHiCeoRJrRlUUcexWBBxdCiSciqGD/qZCpUdQcX99gHYgJhNfiXQseaRkuH8c/ggeOFS+V3e37D+PEJWtl1ShkoBBv477hz5UeGuq85oai3+ME2v3rDkQbjMUIU0NHx8slQDhgL0FPenaaHPgyw0BrCcA1nFSLi1wKCAQEAkVDS0GZKc2xieZ/KBCxtogiR7bAwoNFngL4JgtfJokc3qVF4nb4uMekwXvYbsj89UwdjK0wNiUHoMjO7tG/uBZX3/1yvVs0eWcxeL0u+PkKnKjYO+MI8CW3ilt9bX5XRl3FwESbTDC21uEUsqCm9m5ySxc8h+A+9uHkzou3QXsfKc/unPO+5M4DF7zKChd+F1YFDRALhtrK6IvAJLcs0HtXBQpuXGEkrxUURDIPUeX63QgvBvDKBuy7WAE1i+jU5AQud4aLKxohIjYnPyYsNrfr0lghkLFWY6PrJiS/LCpBEfEsCyibr7sQRACpq97ulXi+RJfZOcwsmm1veRbkpyQKCAQAaVP0l0Pq6pHbdyzLpyCQsCRMaNtGyrXbyMSEIzfGz+i/zhHCgLoMC3HNycfQaJv5/wTPv+3fBRXPYWcEmjbJez0V+EFHPZqBg2tnuOusGCCdWNHK+NJsZz1MY+1yFyoP+NisMfnCh05JWDxtm6D+YdzSawosdiF+iwLydEQf9FHP/yeBOAnLtXR6B/MHTqtglFzl/06co/3NkZuEbGpCS2VX8ekFS4xw9IGv7I5kZ+5nnMX7O3HY5O2MK2baO126cmKkxdzkjQili2+IeSPS8eiS6zIi1bx2RzeEYp/kC90vTc7f8JmJWbjPkcw2nMh0Kb2VvfIL15u/0YrV5sfW4


        host: 172.105.48.59
        username: root
        script: |
          pm2 delete all
          cd /main/epic-300/epic-300
          git pull
          npm install
          node server.js
